diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('',views.IndexView.as_view(), name="index"),
    path('inquiry/',views.InquiryView.as_view(), name="inquiry"),
]

private_diary/urls.py
from django.contrib import admin
from django.urls import path,include

"""
URL configuration for private_diary project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('diary.urls')),
]

diary/models.py
from django.db import models

# Create your models here.

diary/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
#django.coe.mail.Email.EmailMessageクラスを使ってメール送信する
#このクラスはBccやメール添付も行うことができる。取扱いが難しいこともない。

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea)

    def send_email(self):
        name = self.cleaned_data['name']<!-- 2-->
#引数のselfから「self.cleaned_data'<フィールド名>'のようにして、前節のビューの時と同様にフォームバリデーションを通ったユーザ入力値を取得できる
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ{}'.format(title)
        message = '送信者名:{0}?\nメールアドレス:{1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
#送信元(from_email)と宛先(to_list)は、settings.pyで設定されたデータベースパスワードのように環境変数からセットする
        to_list = [
            os.environ.get('FROM_EMAIL')
#送信元from_emailと宛先to_listはsettings.pyで設定したデータベースのパスワードのように環境変数からセットする。
#ただし開発環境では、これらの値がブランクでも動作に支障がないためPyCharmで環境変数を設定している
        ]
        cc_list = [
            email
        ]
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)<!-- 4--><!-- -->
        message.send()<!-- 5--><!-- -->
#EmailMessageインスタンスを作成して、sendメソッドを呼び出す

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力して下さい'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力して下さい'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力して下さい'
        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力して下さい'

# __init__メソッドの中でself.fieldを編集することでcss属性を操作している
# 操作内容はBootstrapのフォーム用クラスform-controlとplaceholderを追加している

diary/views.py
import logging

from django.urls import reverse_lazy
#URLを指定する際はreverse_lazy関数でURLのハードコーティングを避ける。
#reverse_lazy('<urls.pyのapp_name>:<ルーティングにつけたname>')

from django.shortcuts import render
from django.views import generic
from .forms import InquiryForm

logger = logging.getLogger(__name__)
#loggerを取得
#logger.<ログレベル>(<出力内容>]

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')
    #FormViewはクラス変数にURLを指定するだけで、処理に問題が無かった時に指定URLにリダイレクトする

def form_valid(self, form):
#フォームバリデーションに問題なければ実行されるメソッド
#フォームバリデーションを通ったユーザ入力値を↓の形でとりだせる
#form.cleaded_data['<フィールド名>']
    form.send_email()
    #form.pyにメール送信メソッドを呼び出す
    logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
    #ビューからログを出力
    return super().form_valid(form)

diary/templates/base.html
{%  load static %}<!-- 1--><!-- loadタグでstaticタグを使えるようにしている-->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title><!-- 2--><!-- 各ページのテンプレで、タイトルをここに埋め込む。blockタグにtitleと名前をつけて他のblockタグと区別-->
    <link rel="icon" type="image/x-icon" href="{%  static 'assets/favicon.ico'%}"/><!-- 3--><!-- 静的ファイルのパスを相対パスで記述-->

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/ll.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!--Core theme CSS (include Bootstrap) -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet" /><!-- 4--><!-- 静的ファイルのパスを相対パスで記述-->

    <!--My style -->
    <link rel="stylesheet" type="text/css" href="{%  static 'css/mystyle.css' %}"><!-- 5--><!-- 静的ファイルのパスを相対パスで記述。この後に独自CSSを追加するため、あらかじめmystyle.cssを読み込む設定を書く-->
    {% block head %}{% endblock %}<!-- 6--><!-- 各ページのテンプレでページ固有のhead情報をここに埋め込む-->

</head>
<body>
 <div id="wrapper"><!-- 7--><!-- footerを最後に固定するために利用するdivを追加-->
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a><!-- 8--><!-- ナビゲーションバーに表示するPRIVATE DIARYにトップページへのリンクを貼る。urlタグでURLの逆引き。diary:indexはdiaryアプリのurls.pyでindexという名前のルーティングを参照する意味-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a><!-- 9--><!-- ナビゲーションバーのリンクがクリックされると文字色を変えてアクティブにしている見た目を出すBootstrapによる効果を出すためのblockタグを使う。各ページのテンプレートでactiveというテキストを埋め込みこれを実現する--><!--ナビゲーションバーのINQUIRYリンクのhref属性に問い合わせページへのリンクを記述する-->
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Log In</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}{% endblock %}<!-- 10--><!-- 各ページのテンプレで必要に応じてヘッダーをここに埋めこむ。blockタグにheaderという名前をつけて他のblockタグと区別する-->
    {% block contents %}{% endblock %}<!-- 11--><!-- 各ページのテンプレでコンテンツをここに埋めこむ。blockタグにcontentsという名前をつけて他のblockタグと区別する-->

    <!--Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; private Diary 2023</p></div>
    </footer>

    <!--Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
 </div>
</body>
</html>

diary/templates/index.html
{% extends 'base.html' %}<!-- 1--><!-- base.htmlのblockタグに埋めこむため、extendsタグを使ってbase.htmlを読み込む-->

{% load static %}<!-- 2--><!-- loadタグを使い、staticタグを使えるようにする-->

{% block title %}Web上にあなた専用の日記ページを保存できるサービス | Private Diary{% endblock %}<!-- 3-->
<!-- ページタイトルをbase.htmlのtitleという名前をつけたblockタグに埋めこむ-->
{% block header %}<!-- 4-->
<!-- ヘッダーをbase.htmlのheaderという名前をつけたblockタグに埋めこむ-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
            <a href="#" class="btn btn-primary btn-xl rounded-pull mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}<!-- 5--><!-- コンテンツをbase.htmlのcontentsという名前のblockタグに埋めこむ-->
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>Web上で作成、編集、削除ができる日記</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="">
                </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">Save Your Diary</h2>
                    <p>あなたの日記をwebに保存</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="">
                </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>会員制のWeb日記サービス</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ:Private Diary{% endblock %}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style"><!-- 1--><!-- CSSでmargin-topを設定するため追加-->
        <form method="post">
            {% csrf_token %}<!-- 2--><!-- CSRP対策用タグ。POST通信でこのタグをつけていないとDjangoはデフォで403エラーを返す-->
            {{ form.non_field_errors }}<!-- 3--><!-- cleanメソッドなどで発生するフィールドにまたがるエラーを取得できる-->
            {% for field in form %}<!-- 4--><!-- formフィールドを１つずつ取り出せる-->
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong><!-- 5--><!-- formフィールドからラベルやエラー情報を取得する-->
                </label>
                {{ field }}
                {{ field.errors }}<!-- 6--><!-- フィールド単位のエラーを取得-->
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}